---

- name: Setup
  include: setup.yml

- name: Write config
  become: true
  become_user: "{{ grafana_install_user }}"
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_file }}"
    group: "{{ grafana_group }}"
    backup: yes
  notify:
    - restart grafana
  tags:
    - grafana
    - config

- name: start grafana service
  become: true
  become_user: "{{ grafana_install_user }}"
  service:
    name: grafana-server
    state: started
    enabled: yes
  tags:
    - grafana
