---

- name: Ensure the system can use the HTTPS transport for APT
  become: true
  become_user: "{{ grafana_install_user }}"
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport
  tags:
    - grafana
    - packages

- name: Install HTTPS transport for APT
  become: true
  become_user: "{{ grafana_install_user }}"
  apt:
    name: "apt-transport-https"
    state: present
  when: not apt_https_transport.stat.exists
  tags:
    - grafana
    - packages

- name: Download apt key
  become: true
  become_user: "{{ grafana_install_user }}"
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    state: present
  tags:
    - grafana
    - packages

# Always use debian wheezy for every distrib
# According to http://docs.grafana.org/installation/debian/
- name: Add apt repository
  become: true
  become_user: "{{ grafana_install_user }}"
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/stable/debian/ wheezy main"
    filename: "grafana"
    state: present
  tags:
    - grafana
    - packages

- name: Install package
  become: true
  become_user: "{{ grafana_install_user }}"
  apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - restart grafana
  tags:
    - grafana
    - packages
